server:
  port: 5210
spring:
  application:
    name: im-server-prod
  redis:
    host: 192.168.137.100
    port: 6379
    timeout: 7200ms
    lettuce:
      pool:
        max-idle: 8
  rabbitmq:
    host: 192.168.137.100
    username: im
    password: im123
  data:
    mongodb:
      uri: mongodb://im:im123@192.168.8.11:27017/im

im:
  zk:
    register: false
    addr: 127.0.0.1:2181
    connect-timeout: 15000
    root: /im_route