server:
  port: 5220
spring:
  application:
    name: im-client-prod
  redis:
    host: 192.168.137.100
    port: 6379
    timeout: 7200ms
    lettuce:
      pool:
        max-idle: 8
  rabbitmq:
    host: 192.168.137.100
    username: im
    password: im123
  data:
    mongodb:
      uri: mongodb://im:im123@192.168.137.100:27017/im

