server:
  port: 5200
spring:
  application:
    name: im-server-prod
  redis:
    host: 192.168.137.100
    port: 6379
    timeout: 7200ms
    lettuce:
      pool:
        max-idle: 8
  rabbitmq:
    host: 192.168.137.100
    username: im
    password: im123
  data:
    mongodb:
      uri: mongodb://im:im123@192.168.137.100:27017/im

im:
  zk:
    register: true
    addr: 127.0.0.1:2181
    connect-timeout: 15000
    root: /im_route
  server:
    ip: 127.0.0.1
    socket-port: 12000
    websocket-port: 12010
    heartbeat-time: 30